package-repositories:
 - type: apt
   ppa: ucdev/uc-staging-ppa
   priority: always

parts:
  uefi-boot-assets:
    plugin: nil
    stage-packages:
      - grub-efi-${CRAFT_TARGET_ARCH}-signed:${CRAFT_TARGET_ARCH}
      - shim-signed:${CRAFT_TARGET_ARCH}
    override-build: |
      cat << EOF > "${CRAFT_PART_INSTALL}"/cmdline.extra
      __BOOTLOADER_BOOTARGS__
      console=tty1
      EOF

      # Set some variables that depend on the architecture
      grub_target=x86_64
      grub_bin=grubx64.efi.signed
      shim_bin=shimx64.efi.dualsigned
      if [ "${CRAFT_TARGET_ARCH}" = arm64 ]; then
          grub_target=arm64
          grub_bin=grubaa64.efi.signed
          shim_bin=shimaa64.efi.dualsigned
      fi

      # Make sure we have signatures from the UC certificates
      shim_path="${CRAFT_PART_INSTALL}"/usr/lib/shim/$shim_bin
      grub_path="${CRAFT_PART_INSTALL}"/usr/lib/grub/"${grub_target}"-efi-signed/$grub_bin
      #sbverify --list "${shim_path}" | grep -E 'Canonical Ltd. Secure Boot Signing \(Ubuntu Core'
      #sbverify --list "${grub_path}" | grep -E 'Canonical Ltd. Secure Boot Signing \(Ubuntu Core'

      # Move shim/grub to the expected path
      install -m 644 "${shim_path}" "${CRAFT_PART_INSTALL}"/shim.efi.signed
      install -m 644 "${grub_path}" "${CRAFT_PART_INSTALL}/${grub_bin%.signed}"

      # Remove all the bits we do not need, keeping changelogs and copyrights
      # (using organize/prime is not possible due to different names per arch - x64/aa64)
      find "${CRAFT_PART_INSTALL}"/ -type f,l \
                -not -path "${CRAFT_PART_INSTALL}"/shim.efi.signed \
                -not -path "${CRAFT_PART_INSTALL}/${grub_bin%.signed}" \
                -not -path "${CRAFT_PART_INSTALL}/usr/share/doc/grub-efi-${CRAFT_TARGET_ARCH}-signed"/'*' \
           -and -not -path "${CRAFT_PART_INSTALL}"/'usr/share/doc/shim-signed/*' \
           -delete
      find "${CRAFT_PART_INSTALL}"/ -type d -empty -delete

      # grub.conf lets snapd identify grub as the bootloader on boot
      install -m 644 /dev/null "${CRAFT_PART_INSTALL}"/grub.conf

build-packages:
  - sbsigntool

assumes:
  - snapd2.60.1
