volumes:
  ubuntu-core:
    structure:
      - name: ubuntu-seed
        content:
          - source: $kernel:dtbs/dtbs/
            target: /
          - source: boot-assets/
            target: /
          - source: u-boot-bin/
            target: /
