volumes:
  ubuntu-core:
    structure:
      - name: ubuntu-seed
        content:
          - source: grubaa64.efi
            target: EFI/boot/grubaa64.efi
          - source: shim.efi.signed
            target: EFI/boot/bootaa64.efi
          - source: $kernel:dtbs/dtbs/
            target: /
      - name: ubuntu-boot
        content:
          - source: grubaa64.efi
            target: EFI/boot/grubaa64.efi
