parts:
  rkbin:
    plugin: dump
    source: https://github.com/rockchip-linux/rkbin.git
    source-type: git
    source-depth: 1
    organize:
      "*": rkbin
    prime:
      - -*

  u-boot:
    after:
      - rkbin
    override-build: |
      cat << EOF >> configs/__BOOTLOADER_DEFCONFIG__
      CONFIG_FIT=y
      CONFIG_LOCALVERSION_AUTO=n
      EOF
      make __BOOTLOADER_DEFCONFIG__

      cp "${CRAFT_PROJECT_DIR}"/u-boot-patch/*.patch ./
      patch -p1 < *.patch
      make BL31=$(find "${CRAFT_STAGE}"/rkbin -name "rk3588_bl31*.elf") spl/u-boot-spl.bin u-boot.dtb u-boot.itb \
        -j$(nproc) LOCALVERSION="-uc22"
      RK3588_BIN=$(find "${CRAFT_STAGE}"/rkbin/bin/rk35/ -name "rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v*.bin")
      tools/mkimage -n rk3588 -T rksd -d "${RK3588_BIN}":spl/u-boot-spl.bin idbloader.img
      cp idbloader.img "${CRAFT_PART_INSTALL}"/bootloader.bin
      cp u-boot.itb "${CRAFT_PART_INSTALL}"/

      # Copy licenses
      mkdir -p "${CRAFT_PART_INSTALL}"/usr/share/doc/u-boot
      cp -a Licenses/* "${CRAFT_PART_INSTALL}"/usr/share/doc/u-boot

      mkenvimage -s 4096 -o "${CRAFT_PART_INSTALL}"/boot.sel - < /dev/null
      touch "${CRAFT_PART_INSTALL}"/uboot.conf
