parts:
  fip:
    after:
      - u-boot
    plugin: nil
    source: https://github.com/LibreELEC/amlogic-boot-fip.git
    source-type: git
    source-depth: 1
    source-branch: master
    override-build: |
      mkdir output
      ./build-fip.sh khadas-vim ${CRAFT_STAGE}/u-boot.bin output/
      dd if=output/u-boot.bin.sd.bin of=${CRAFT_PART_INSTALL}/bootloader.bin bs=512 skip=1 conv=fsync
      dd if=output/u-boot.bin.sd.bin of=${CRAFT_PART_INSTALL}/mbr.bin bs=1 count=440 conv=fsync
