# NXP i.MX93 quad core 32 GB RAM
DEVICE="i.MX_93QSB"
ARCH=arm64
ASSERTION_FILE=ubuntu-core-22-dangerous-model-arm64.assert
CROSS_COMPILE=
CROSS_COMPILE_DEB_PACKAGE=

BSP_GIT_BRANCH=lf-6.6.36-2.1.0
PARTITION_SCHEMA=gpt
BOOTLOADER_GIT_SOURCE=https://github.com/nxp-imx/uboot-imx
BOOTLOADER_GIT_BRANCH=lf-6.6.36-2.1.0
BOOTLOADER_DEFCONFIG=imx93_9x9_qsb_defconfig
BOOTLOADER_BINARY=u-boot.bin
BOOTLOADER_BOOTARGS="console=ttyLP0,115200 earlycon"
BOOTLOADER_BOOTCMD='bootm ${fitloadaddr}:kernel-uc ${fitloadaddr}:ramdisk-uc ${fdt_addr_r}'
UEFI_SUPPORT=true

CLOUD_INIT_ENABLED=true

MMC_DEV_NUM=1
KERNEL_LOAD_ADDR=0x80400000
RAMDISK_LOAD_ADDR=0x83800000
FDT_LOAD_ADDR=0x83000000
FIT_LOAD_ADDR=0x8a000000

ITS_KERNEL_COMPRESSION="gzip"
ITS_ARCH=arm64
ITS_FDT_NAME=imx8mp-evk.dtb

KERNEL_GIT_SOURCE=https://github.com/nxp-imx/linux-imx
KERNEL_GIT_BRANCH=lf-6.6.36-2.1.0
KERNEL_DEFCONFIG=defconfig
