volumes:
  ubuntu-core:
    structure:
      - name: spl
        offset: 2097152
        size: 1M
        type: 0C,2E54B353-1271-4842-806F-E436D6AF6985
        content:
          - image: u-boot-spl.bin.normal.out
      - name: bootloader
        offset: 4194304
        size: 8M
        type: 0C,5B193300-FC78-40CD-8002-E86C45580B47
        content:
          - image: visionfive2_fw_payload.img
