assumes: [kernel-assets]

parts:
  kernel-yaml:
    plugin: nil
    override-build: |
      mkdir -p "${CRAFT_PART_INSTALL}"/meta
      cat << EOF > "${CRAFT_PART_INSTALL}"/meta/kernel.yaml
      assets:
        dtbs:
          update: true
          content:
            - dtbs/
      EOF

  firmware-rename:
    plugin: nil
    override-prime: |
      mv "${CRAFT_PRIME}"/firmware/brcm/brcmfmac43455-sdio.bin \
        "${CRAFT_PRIME}"/firmware/brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.bin
