name: gadget-snap
base: core22
version: '0.1'
summary: Test gadget snap
description: |
  This is a test gadget snap

type: gadget
architectures:
  - build-on: amd64
    build-for: __ARCH__

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  u-boot:
    plugin: nil
    source: __BOOTLOADER_GIT_SOURCE__
    source-type: git
    source-depth: 1
    source-branch: __BOOTLOADER_GIT_BRANCH__
    build-environment:
      - on amd64:
        - CROSS_COMPILE: __CROSS_COMPILER__
    override-build: |
      cat << EOF >> configs/__BOOTLOADER_DEFCONFIG__
      CONFIG_FIT=y
      CONFIG_LOCALVERSION_AUTO=n
      EOF
      make __BOOTLOADER_DEFCONFIG__

      if [ '__ATF_IS_REQUIRED__' == 'true' ]; then
        if [ -f ${CRAFT_STAGE}/bl31.bin ]; then
          cp ${CRAFT_STAGE}/bl31.bin ./
        else
          echo "Error: bl31.bin not found"
          exit 1
        fi
      fi

      if [ '__SCP_IS_REQUIRED__' == 'true' ]; then
        if [ -f ${CRAFT_STAGE}/scp.bin ]; then
          cp ${CRAFT_STAGE}/scp.bin ./
        else
          echo "Error: scp.bin not found"
          exit 1
        fi
      fi

      make -j$(nproc) LOCALVERSION="-uc22"

      # Copy licenses
      mkdir -p ${CRAFT_PART_INSTALL}/usr/share/doc/u-boot
      cp -a Licenses/* ${CRAFT_PART_INSTALL}/usr/share/doc/u-boot

      if [ '__BOOTLOADER_BINARY_RENAME__' == 'false' ]; then
        cp __BOOTLOADER_BINARY__ ${CRAFT_PART_INSTALL}/
      else
        cp __BOOTLOADER_BINARY__ ${CRAFT_PART_INSTALL}/bootloader.bin
      fi

      mkenvimage -s 4096 -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null
      touch ${CRAFT_PART_INSTALL}/uboot.conf
    prime:
      - -__BOOTLOADER_BINARY__

  boot-script:
    plugin: dump
    source: boot-script
    override-build: |
      mkimage -C none -A arm -T script -d boot.cmd ${CRAFT_PART_INSTALL}/boot.scr

  cloud-init-conf:
    plugin: dump
    source: cloud-init

build-packages:
  - bc
  - bison
  - build-essential
  - device-tree-compiler
  - flex
  - libssl-dev
  - python3-dev
  - python3-pycryptodome
  - python3-pyelftools
  - swig
  - u-boot-tools
  - on amd64:
    - __CROSS_COMPILER_DEB_PACKAGE__
    - __SCP_CROSS_COMPILER_DEB_PACKAGE__
